# Generated by Django 3.2.12 on 2025-10-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docSys_app', '0004_alter_members_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='has_staff_privileges',
            field=models.BooleanField(default=False),
        ),
    ]
